name: MyoPong
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - stable-baselines3[extra]
    - wandb
    - myosuite
    - gymnasium
    - numpy
    - mujoco-py
    - joblib
    - scikit-learn
    - sb3_contrib
    - imageio-ffmpeg