name: MyoPong
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - stable-baselines3[extra]
    - stable-baselines3-contrib
    - wandb
    - myosuite
    - gymnasium
    - numpy
    - mujoco-py